[phases.setup]
nixPkgs = ["python310Full", "nodejs", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel"]

[phases.install]
cmds = ["python install_deps.py"]

[phases.build]
cmds = ["echo 'Build jรก foi feito no install'"]

[start]
cmd = "bash run.sh" 