[phases.setup]
nixPkgs = ["python310Full", "nodejs", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip setuptools wheel",
    "bash install.sh"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "bash run.sh" 