[phases.setup]
nixPkgs = ["python310Full", "nodejs_18", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r backend/requirements.txt",
    "cd frontend && npm install",
    "cd frontend && npm run build"
]

[phases.build]
cmds = ["echo 'Dependencies installed and frontend built'"]

[start]
cmd = "cd backend/app && python -m uvicorn main:app --host 0.0.0.0 --port $PORT" 